apiVersion: v1
kind: Service
metadata:
  name: access-management-node-port
spec:
  # ! NodePort -> only for development purpose
  type: NodePort
  selector:
    app: access-management
  ports:
    - port: 4003
      targetPort: 4003
      protocol: TCP
      name: access-management
