apiVersion: v1
kind: Service
metadata:
  name: access-management-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: access-management
  ports:
    - name: access-management
      protocol: TCP
      port: 4000
      targetPort: 4000